### ISSUE TITLE
External USB port

### ISSUE THREAD

**Issue by lorentrogers** [technomancy/atreus#20]
I really love this keyboard, but I'd extra love it if I could attach / detach the USB cable from it. I'm thinking of mounting a USB port to the back of it and wiring up the inside so that there's no chance of the cord being pulled out from the processor. (Which has happened to me a couple times...) This requires the whole board to be unscrewed, the cable plugged back in, then everything put back together.

Instead, what I'd propose is adding something like this to the back of the case:
http://www.mouser.com/ProductDetail/TE-Connectivity-AMP/2108877-1/?qs=sGAEpiMZZMshRPDbDyJ0ATDgOjL7etQ%2fBnVtRtrknVI%3d
Then, you could hard-wire the processor to the mount and just plug in a cable to the outside, much like how you'd connect a regular usb device.

I've not done much research on this -- is there a processor that allows for an external USB port? (Instead of the soldered one that's on the current design.)

I'd like to prototype this out, but figured I'd check to see if it's been done yet.

**Comment by lorentrogers** [comment]
Alternatively, could the PCB be updated to move the controller farther back toward the cable opening? Looking at the current design, it makes sense to have it right in the center, because it keeps things as compact as possible. Moving the port to the top would be less efficient internally, but possibly more useful. Thoughts?

**Comment by technomancy** [comment]
Loren Rogers <notifications@github.com> writes:

> I really love this keyboard, but I'd extra love it if I could attach /
> detach the USB cable from it. I'm thinking of mounting a USB port to
> the back of it and wiring up the inside so that there's no chance of
> the cord being pulled out from the processor. (Which has happened to
> me a couple times...) This requires the whole board to be unscrewed,
> the cable plugged back in, then everything put back together.

I would strongly suggest instead of doing this that you add some strain
relief to the cable you are using. Wrap some electrical tape around the
cord at the point right below where it exits the case, and it will be
too thick to come out even if you tug on it.

I will add a note suggesting this to the assembly guide. Not all USB
cables need it since some of them have a longer head that already
prevents this from happening, but some may benefit from it.

> Instead, what I'd propose is adding something like this to the back of
> the case:
> http://www.mouser.com/ProductDetail/TE-Connectivity-AMP/2108877-1/?qs=sGAEpiMZZMshRPDbDyJ0ATDgOjL7etQ%2fBnVtRtrknVI%3d
> Then, you could hard-wire the processor to the mount and just plug in
> a cable to the outside, much like how you'd connect a regular usb
> device.

The problem here is that you would have to cut a notch out of the spacer
layer in order to allow the screws to both hold the USB connector in
place *and* keep the spacer secure. This kind of cut is impossible to do
with a laser cutter since it is not 2-dimensional; it must be done by
hand during construction, which adds more failure-prone steps to the
assembly process. The repeated removal and insertion of the cable into
the port leads to an increased chance of failure, as does having it
exposed on the outside of the case.

> I've not done much research on this -- is there a processor that
> allows for an external USB port? (Instead of the soldered one that's
> on the current design.)

You wouldn't have to change the controller at all for this; see the
Ergodox USB port:

  https://d3jqoivu6qpygv.cloudfront.net/img_bucket/ergodox/ergodox_assembly_19.jpg

This makes sense on the Ergodox because it is designed to be used in a
stationary position on a desk; the Atreus is intended to be taken around
with you in your laptop bag, which calls for a design that prioritizes
durability.

-Phil

**Comment by lorentrogers** [comment]
Good point about the tape I'll probably end up doing that. 

I guess one of the main reasons I'd want an external port would be the ability to swap out cables. Because this keyboard is now my go-to for travel, I'd prefer to keep a short cable in my bag, and have a long one attached at my desk. (I use one of those Thinkpad laptop bases.) Having an external usb mount would also let me quickly move the keyboard to different machines by just swapping out the cable.

My main inspiration for this idea comes from how Wacom handles their cables. The super old models had the cables baked right into the board, but the newer ones have a usb port on the outside. The port durability has been less of an issue for me than cables going bad. (I've never had a port go bad, to my knowledge.) It's only *because* I know how this thing is put together that I'm thinking about it. Every time I go to pack, up my stuff, I reach for the back to unplug it, and then have to remember that I can't, because it's stuck inside the housing.

Since the controller already has a port built in, I figured there may be a way to make cable swapping an option. I imagine that any modification here would require that the case's layout will need to be slightly modified, but I think this would really only require that the space at the top be made a little wider. Or, if we find the right part, it may be possible to modify the board just enough so that it supports both hard-wired (as it is today) and ported versions.

Looking through the design files, it looks like the spacer layer is just a single piece? (Looking at my board, it seems like three layers glued together?) Could this possibly be split into two pieces? If so, one of the spacer layers could possibly be cut with an extra wide port at the top. Then, we could either put a mount between the layers that has the USB port, or we could put in a pre-cut spacer. 

Here's a quick sketch of what I'm thinking: 
![fullsizerender](https://cloud.githubusercontent.com/assets/1090824/12985596/80aa402a-d0c1-11e5-834f-64a6c87538cb.jpg)
(Let me know what I can clarify -- I'm sure my sketch isn't totally clear.)

**Comment by lorentrogers** [comment]
Also, is this the material used to make the cases? 
http://www.ponoko.com/make-and-sell/show-material/87-veneer-mdf-cherry#main-image

**Comment by technomancy** [comment]
I think my original message was a bit unclear; I don't think this is a
good idea for the default design of the kit, but I am 100% in favor of
you experimenting and customizing for yourself to try to find a setup
that works well for you. Hackability is really what this project is all
about. If you want to document what you have done as an option for
others who want to put a bit of extra work into their board, that would
be great too.

> I guess one of the main reasons I'd want an external port would be the
> ability to swap out cables. Because this keyboard is now my go-to for
> travel, I'd prefer to keep a short cable in my bag, and have a long
> one attached at my desk.

Have you thought about just using an M->F extension cable at your desk
so you can plug the short cable directly into that?

> The port durability has been less of an issue for me than cables going
> bad.  (I've never had a port go bad, to my knowledge.)

I don't doubt it, but you're comparing a port that was built into an
injection-molded plastic case and assembled in a factory to one that
is hand-assembled into wood by someone who has never done it
before. There are so many more things that can go wrong in the process
of assembling a kit.

> Looking through the design files, it looks like the spacer layer is
> just a single piece? (Looking at my board, it seems like three layers
> glued together?) Could this possibly be split into two pieces?

It could be done, but it would increase the cost of the laser cutting
and case materials. A single piece of ply (which happens to be made out
of thinner pieces) is faster to cut, as well as being simpler to source
and assemble.

> Also, is this the material used to make the cases?

The cases for kits I ship are cut in birch ply. I would be a hesitant to
recommend MDF in general, though for the spacer layer it probably
doesn't matter much.

In any case, if you do try building your own spacer layer as a one-off
and making room to mount an external port, I would be interested in seeing
photos of the process.

**Comment by lorentrogers** [comment]
Thanks for clarifying - I totally agree. Yes, at the moment I'm using a USB extender at my desk, and it does work ok. 

I think I'll do some experimentation on my end to see if I can come up with a working solution. I'll definitely post any updates.
