### ISSUE TITLE
KeyUp and KeyDown events - fn layer sends a different KeyUp event

### ISSUE THREAD

**Issue by srustamo** [technomancy/atreus#21]
I'm using `teensy2` branch (which seems to be gone from the repo).

`fn` layer <kbd>*</kbd> seems to send the following sequence:

    FlagChanged - Shift_R - flag Shift
    KeyDown        - *           - flag Shift
    FlagChanged - Shift_R  -
    KeyUp             - 8

This last KeyUp is causing problem in VirtualBox Win7. It registers <kbd>8</kbd> instead of <kbd>*</kbd>. Other key presses send same KeyDown and KeyUp sequences. Only `fn` layer seems to differ.

Is there anyway force KeyUp to send the same sequence as KeyDown for `fn` layer?

Sent similar question to atreus@freelists.org, hope no problems with writing here, too.

**Comment by technomancy** [comment]
I realized the readme here didn't mention the change to using the TMK firmware, which shouldn't have this problem. Fixed in 0b214f2.
