### ISSUE TITLE
DEPRECATED: child() will be removed in future releases. Use children() instead. 

### ISSUE THREAD

**Issue by Narann** [technomancy/atreus#28]
Just for your information. I'm using OpenSCAD 2015.3 and got this warning:

```
Compiling design (CSG Tree generation)...
DEPRECATED: child() will be removed in future releases. Use children() instead. 
Compiling design (CSG Products generation)...
Geometries in cache: 225
Geometry cache size in bytes: 485920
CGAL Polyhedrons in cache: 0
CGAL cache size in bytes: 0
Compiling design (CSG Products normalization)...
Normalized CSG tree has 230 elements
Compile and preview finished.
Total rendering time: 0 hours, 0 minutes, 0 seconds
```

As you guess it's not a problem at all but I send it this just FYI.

I take this as an opportunity to say a big **THANKS** for having make this keyboard open source. I build my own Atreus as a hobby project and love it. I now plan to do a bigger one adding one column on the left and on the right (I know it's no more a "real" Atreus but I love key placement). Thanks again for make me hacking a real electronic project, you must be a nice guy! :)

**Comment by technomancy** [comment]
Looks like this is fixed in #32; thanks for the heads up.
