### ISSUE TITLE
What pins to use on Pololu A-Star Micro?

### ISSUE THREAD

**Issue by JacobRoth** [technomancy/atreus#29]
I'm building a hand-wired Atreus, and I bought a Pololu A-Star Micro as called for on the bill of materials. However, the hand-wired build guide only provides instructions (as in, what pins to wire the rows and columns to)  for the Teensy 2. What pins should I solder to on a Pololu A-Star Micro?

**Comment by technomancy** [comment]
This ended up getting answered on the mailing list, but in case anyone else is looking for the info:

https://www.freelists.org/post/atreus/Handwired-Atreus-build-with-Pololu-AStar-Micro-Which-pins-should-I-use-for-what,2
