### ISSUE TITLE
alps-top-plate-3mm.eps is only a single layer, the others aren't

### ISSUE THREAD

**Issue by hartzell** [technomancy/atreus#31]
This might be a bug, it might just be an observation.

I'm getting Ponoko to cut layers for my new keyboard.

I'm using Affinity Designer to make a single eps file from the eps files in the repo, that contains the three layers that I want,  adjusted as necessary (the strokes need to be blue and the lines need to be narrower [and I'm etching my name on the bottom...]).

`alps-switch-plate-3mm.eps` and `bottom-plate-3mm.eps` are assembled from multiple layers and I can open the individual bits and adjust as required.

When I open `alps-top-plate-3mm.eps` it just shows up at a single layer, there's not bunch of individual layers.

I tried adjusting everything on that one layer but Ponoko came back with an error about that part not being vector art.

I've attached snapshots of the layer pallete for the top plate and the switch plate.

Switch plate:

<img width="391" alt="switch-plate-eg" src="https://user-images.githubusercontent.com/312978/29435006-05d4e34e-835a-11e7-9f1b-648d06f28764.png">

Top plate:

<img width="379" alt="top-plate-eg" src="https://user-images.githubusercontent.com/312978/29435010-0bb04272-835a-11e7-8468-3eff819f4b85.png">

Is there a way to make a version of the top plate available that's as the switch plate eps file is?

Thanks!

**Comment by technomancy** [comment]
I've never used Affinity Designer, but none of the files are intended to have multiple layers within a file. Each layer should be its own file.

If you open them in Inkscape all the different files should behave the same way; you can break apart the individual pieces into the shapes that make them up.

**Comment by hartzell** [comment]
I'll give that a try.  Thx!

**Comment by hartzell** [comment]
I've installed inkscape and ghostscript (for the ps2pdf converter) and I'm still stuck.

When I open the alps-switch-plate-3mm.eps file I can (given sufficient dexterity) select indivdual drill holes or a side of switch opening or a half of the outline.

When I open the alps-top-plate-3mm.eps, whenever I select anything I select *everything*.  It's as if there's only object/path in that file and it includes all of the shape (I'm sure I'm not using inkscape/vector graphics words properly).

@technomancy -- Can you confirm that you can select individual elements from the top plate file?

**Comment by technomancy** [comment]
There's a "break apart" option in one of the menus that will allow you to manipulate the pieces individually.

**Comment by hartzell** [comment]
That was the magic I was missing.  Thank you! :+1:
